---
- name: Install tools
  package:
    name:
      - kubectx
      - gh
      - jq
      - fzf
      - yq
      - snapd
      - micro
    state: present
  become: yes
  when: is_linux == 'true'

- name: Add tfenv to PATH
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: 'export PATH="$PATH:{{ ansible_env.HOME }}/.tfenv/bin"'
    state: present
    create: yes
  when: is_linux == 'true'

