---
- name: Install tools
  package:
    name:
      - kubectx
      - gh
      - jq
      - yq
      - snapd
      - micro
      - python3-pip
      - dnsutils
      - fzf
    state: present
  become: yes
  when: is_linux == 'true'

- name: Install aws-cli with Snap classic
  snap:
    name: aws-cli
    classic: true
    state: present
  become: yes
  when: is_linux == 'true'

- name: Add tfenv to PATH
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: 'export PATH="$PATH:{{ ansible_env.HOME }}/.tfenv/bin"'
    state: present
    create: yes
  when: is_linux == 'true'

- name: Configure fzf key bindings
  shell: |
    echo '[ -f /usr/share/doc/fzf/examples/key-bindings.bash ] && source /usr/share/doc/fzf/examples/key-bindings.bash' >> "{{ ansible_env.HOME }}/.bashrc"
    echo '[ -f /usr/share/bash-completion/completions/fzf ] && source /usr/share/bash-completion/completions/fzf' >> "{{ ansible_env.HOME }}/.bashrc"
  when: is_linux == 'true'
