---
- hosts: localhost
  become: yes
  tasks:
    - name: Get logged-in username from environment variables
      shell: echo $USER
      register: current_user
      changed_when: false

    - name: Set ansible_user variable
      set_fact:
        ansible_user: "{{ current_user.stdout }}"

    - name: Get the user shell
      shell: "getent passwd {{ ansible_user }} | awk -F: '{ print $7 }'"
      register: user_shell_result
      changed_when: false

    - name: Set user_shell variable
      set_fact:
        user_shell: "{{ user_shell_result.stdout }}"

    - block:
      - name: Install the 'Development tools' package group
        ansible.builtin.yum:
          name: "@Development tools"
          state: present

      - name: Install prereq rpm packages
        ansible.builtin.yum:
          name: "{{ packages }}"
          state: present
        vars:
          packages:
            - curl
            - file
            - git
            - procps-ng

      - name: Install Fedora 30+ rpm package
        ansible.builtin.yum:
          name: libxcrypt-compat
          state: present
        when:
          - ansible_distribution == "Fedora"
          - ansible_distribution_major_version >= "30"
      when:
        - (ansible_pkg_mgr == "yum" or ansible_pkg_mgr == "dnf") and (ansible_os_family == "RedHat" or ansible_os_family == "Rocky")

    - block:
      - name: Install prereq deb packages
        ansible.builtin.apt:
          update_cache: true
          name: "{{ packages }}"
          state: present
        vars:
          packages:
            - build-essential
            - curl
            - file
            - git
            - procps
      when:
        - ansible_pkg_mgr == "apt" and ansible_os_family == "Debian"

    - block:
      - name: Install prereq rpm packages using zypper
        ansible.builtin.zypper:
          name: "{{ packages }}"
          state: present
        vars:
          packages:
            - curl
            - file
            - git
            - procps
      when:
        - ansible_pkg_mgr == "zypper" and ansible_os_family == "Suse"

    - name: Install gcc
      community.general.homebrew:
        name: gcc
        state: present
      become: no

    - name: Install nvm
      community.general.homebrew:
        name: nvm
        state: present
      become: no

    - name: Install tfenv
      community.general.homebrew:
        name: tfenv
        state: present
      become: no

    - name: Install fzf
      community.general.homebrew:
        name: fzf
        state: present
      become: no

    - name: Post-install fzf
      ansible.builtin.shell:
        cmd: $(brew --prefix)/opt/fzf/install
      become: no

    - name: Install awscli
      community.general.homebrew:
        name: awscli
        state: present
      become: no

    - name: Install kubectl
      community.general.homebrew:
        name: kubectl
        state: present
      become: no

    - name: Install kubectx
      community.general.homebrew:
        name: kubectx
        state: present
      become: no

    - name: Install k9s
      community.general.homebrew:
        name: k9s
        state: present
      become: no

    - name: Install jq
      community.general.homebrew:
        name: jq
        state: present
      become: no

    - name: Install yq
      community.general.homebrew:
        name: yq
        state: present
      become: no

    - name: Install lazygit
      community.general.homebrew:
        name: lazygit
        state: present
      become: no

    - name: Install flyctl
      community.general.homebrew:
        name: flyctl
        state: present
      become: no

    - name: Add aliases to .bashrc
      ansible.builtin.lineinfile:
        path: "/home/{{ ansible_user }}/.bashrc"
        line: "{{ item }}"
        create: yes
      with_items:
        - "alias tf='terraform'"
        - "alias lg='lazygit'"
        - "alias k='kubectl'"
        - "alias kx='kubectx'"
      when: user_shell == "/bin/bash"

    - name: Add aliases to .zshrc
      ansible.builtin.lineinfile:
        path: "/home/{{ ansible_user }}/.zshrc"
        line: "{{ item }}"
        create: yes
      with_items:
        - "alias tf='terraform'"
        - "alias lg='lazygit'"
        - "alias k='kubectl'"
        - "alias kx='kubectx'"
      when: user_shell == "/bin/zsh"
